# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: IBM Dedicated Cloud Object Storage Help
email: twegan@us.ibm.com
description: The definitive Knowledge Base for IBM Dedicated Cloud Object Storage Help
baseurl: "/help-documentation" # the subpath of your site, e.g. /blog
url: "http://ibm-cos-help.github.io" # the base hostname & protocol for your site
twitter_username: tj_egan
github_username:  twegan



# Build settings
permalink: /:title
top-level: /:top-level

kramdown:
  input: GFM
  syntax_highlighter: rouge


#variables
author: /:author

#Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      dateAdded: "June 7th, 2016"
      author: "COS Dedicated IBM Managed Support"
      job-title:

sass:
    style: compressed

collections:
  troubleshooting:
    output: true
    permalink: /troubleshooting/:path/
  api:
    output: true
    permalink: /gettingstarted/api/:path/
  userdocs:
    output: true
    permalink: /openstack/userdocs/:path/
  gettingstarted:
    output: true
    permalink: /gettingstarted/:path/
  commontech:
    output: true
    permalink: /gettingstarted/commontech/:path/
  commonadmin:
    output: true
    permalink: /gettingstarted/commonadmin/:path/
  userguides:
    output: true
    permalink: /gettingstarted/userguides/:path/
